package com.myapps.pacman.levels

import com.myapps.pacman.utils.Position
import com.myapps.pacman.utils.getAmountOfFood

object LevelsData {
    val pacmanGame = listOf(
        LevelStartData(
            mapCharData = CharMaps.mapOne,
            blinkyDefaultPosition = Position(15, 14),
            inkyDefaultPosition = Position(18, 11),
            pinkyDefaultPosition = Position(18, 13),
            clydeDefaultPosition = Position(18, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(17, 19),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 16),
            inkyScatterPosition = Position(6, 11),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(16, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(27, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapOne),
            blinkySpeedDelay = 250,
            isBell = true
        ),
        LevelStartData(
            mapCharData = CharMaps.mapTwo,
            blinkyDefaultPosition = Position(14, 14),
            inkyDefaultPosition = Position(17, 11),
            pinkyDefaultPosition = Position(17, 13),
            clydeDefaultPosition = Position(17, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(16, 18),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 1),
            inkyScatterPosition = Position(6, 26),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(15, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapTwo),
            blinkySpeedDelay = 240,
            isBell = false
        ),
        LevelStartData(
            mapCharData = CharMaps.mapThree,
            blinkyDefaultPosition = Position(14, 14),
            inkyDefaultPosition = Position(17, 11),
            pinkyDefaultPosition = Position(17, 13),
            clydeDefaultPosition = Position(17, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(16, 18),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 1),
            inkyScatterPosition = Position(6, 26),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(15, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapThree),
            blinkySpeedDelay = 240,
            isBell = true
        ),
        LevelStartData(
            mapCharData = CharMaps.mapFour,
            blinkyDefaultPosition = Position(14, 14),
            inkyDefaultPosition = Position(17, 11),
            pinkyDefaultPosition = Position(17, 13),
            clydeDefaultPosition = Position(17, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(16, 18),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 1),
            inkyScatterPosition = Position(6, 26),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(15, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapFour),
            blinkySpeedDelay = 230,
            isBell = false
        ),
        LevelStartData(
            mapCharData = CharMaps.mapFive,
            blinkyDefaultPosition = Position(14, 14),
            inkyDefaultPosition = Position(17, 11),
            pinkyDefaultPosition = Position(17, 13),
            clydeDefaultPosition = Position(17, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(16, 18),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 1),
            inkyScatterPosition = Position(6, 26),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(15, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapFive),
            blinkySpeedDelay = 220,
            isBell = true
        ),
        LevelStartData(
            mapCharData = CharMaps.mapSix,
            blinkyDefaultPosition = Position(14, 14),
            inkyDefaultPosition = Position(17, 11),
            pinkyDefaultPosition = Position(17, 13),
            clydeDefaultPosition = Position(17, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(16, 18),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(7, 5),
            inkyScatterPosition = Position(7, 22),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(15, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapSix),
            blinkySpeedDelay = 210,
            isBell = true
        ),
        LevelStartData(
            mapCharData = CharMaps.mapSeven,
            blinkyDefaultPosition = Position(14, 14),
            inkyDefaultPosition = Position(17, 11),
            pinkyDefaultPosition = Position(17, 13),
            clydeDefaultPosition = Position(17, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(16, 18),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 1),
            inkyScatterPosition = Position(6, 26),
            pinkyScatterPosition = Position(29, 10),
            clydeScatterPosition = Position(29, 19),
            doorTarget = Position(15, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapSeven),
            blinkySpeedDelay = 210,
            isBell = true
        ),
        LevelStartData(
            mapCharData = CharMaps.mapEight,
            blinkyDefaultPosition = Position(13, 14),
            inkyDefaultPosition = Position(16, 11),
            pinkyDefaultPosition = Position(16, 13),
            clydeDefaultPosition = Position(16, 16),
            homeTargetPosition = Position(16, 14),
            ghostHomeXRange = IntRange(15, 17),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 1),
            inkyScatterPosition = Position(6, 26),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(14, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapEight),
            blinkySpeedDelay = 200,
            isBell = false
        ),
        LevelStartData(
            mapCharData = CharMaps.mapNine,
            blinkyDefaultPosition = Position(14, 14),
            inkyDefaultPosition = Position(17, 11),
            pinkyDefaultPosition = Position(17, 13),
            clydeDefaultPosition = Position(17, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(16, 18),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 1),
            inkyScatterPosition = Position(6, 26),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(15, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapNine),
            blinkySpeedDelay = 200,
            isBell = false
        ),
        LevelStartData(
            mapCharData = CharMaps.mapTen,
            blinkyDefaultPosition = Position(14, 14),
            inkyDefaultPosition = Position(17, 11),
            pinkyDefaultPosition = Position(17, 13),
            clydeDefaultPosition = Position(17, 16),
            homeTargetPosition = Position(17, 14),
            ghostHomeXRange = IntRange(16, 18),
            ghostHomeYRange = IntRange(11, 16),
            blinkyScatterPosition = Position(6, 1),
            inkyScatterPosition = Position(6, 26),
            pinkyScatterPosition = Position(30, 1),
            clydeScatterPosition = Position(30, 26),
            doorTarget = Position(15, 14),
            width = 28,
            height = 36,
            pacmanDefaultPosition = Position(26, 14),
            amountOfFood = getAmountOfFood(CharMaps.mapTen),
            blinkySpeedDelay = 200,
            isBell = false
        )
    )
}